
sequence variant: # The type in Biolink
    represented_as: node
    label_in_input: SequenceVariant
    properties:
        CHROM: str
        POS: int
        REF: str
        ALT: str

# Another node type (e.g. of a column of the table).
patient: # Existing in Biolink under another name.
    represented_as: node
    label_in_input: Patient
    synonym_for: case # Actual name in Biolink.
    properties: 
        age: int
        bmi: float
        stage: str
        treatment: str


patient has variant: # Not existing in Biolink…
    # … thus added by Biocypher under:
    is_a: case to phenotypic feature association
    represented_as: edge
    label_in_input: PatientToSequenceVariantAssociation
    source: patient
    target: sequence variant

gene: # The type in Biolink
  represented_as: node
  label_in_input: Gene

variant to gene association: #The type in BioLink
    represented_as: edge
    label_in_input: SequenceVariantToGeneAssociation
    source: sequence variant
    target: gene